### ISSUE TITLE
Error creating Stacks - DNSRecord

### ISSUE THREAD

**Issue by ElCativoGER** [toshke/big-blue-button-cloudformation-cfhl#15]
I am failing creating Stacks. It tries to create and partly goes well. When the template tries to create DNS Entry, it fails. " No hosted zones named *mydomain* found.
What is wrong? 
I am using this domain for long time, so I know it is working.
Please help.

Greting, Alex

**Comment by ElCativoGER** [comment]
Hi Nikola.
After using Google i found an entry wich says, this can come upm when the entry needs some "trailing period". Do you think so, too? 

Greetings, Alex

**Comment by ElCativoGER** [comment]
Found it...
I do not use Rozte53 but entered my Domain in the DNS Record Field for Route53.
Thank you

**Comment by toshke** [comment]
@ElCativoGER i believe you may have left the commend on the youtube video as well...
a) Your domain needs be hosted with Route53
b) If it is not you can still use it, but
   - Create EIP outside of the CloudFormation template given through this repo
   - Point DNS record, let's say `video.example.com` to this new elastic IP address on AWS
   - Render and deploy templates using `external_eip: true` as configuration value. - https://github.com/toshke/big-blue-button-cloudformation-cfhl/blob/master/bbb.config.yaml#L19
You can read more under `Generate and build your own templates` in [README.md](./../README.md)

I guess it would be neat to have Q&A for this common non-default configurations.
