### ISSUE TITLE
freeswitch does not start after reboot

### ISSUE THREAD

**Issue by xerxesxe** [toshke/big-blue-button-cloudformation-cfhl#17]
Hi, thanks for this nice stack. I can't manage to get the Instance running again after an instance reboot or bbb-conf --restart. The freeswitch service does not start anymore and i can't find any false config files. Does not seem to be a false IP. Any Idea?

**Comment by toshke** [comment]
hi @xerxesxe . In all honesty I was focused on infrastructure elements of the BBB, and not expert on software within the box itself. BigBlueButton google groups discussions may be a good place to ask.
