### ISSUE TITLE
Customisation of BBB

### ISSUE THREAD

**Issue by bernardnongpoh** [toshke/big-blue-button-cloudformation-cfhl#18]
Thanks for the CF. I am able to deploy to AWS EC2 instances. Can I customize this BBB to suite my branding. How to do so. 
Thanks for such a wonderful piece of work.

**Comment by toshke** [comment]
hey @bernardnongpoh - what do you mean by 'customise'? You can definetely fork the repository and work on your changes there, or raise PRs :) As for BBB branding and what not, there is excellent documentation on BigBlueButton website - https://docs.bigbluebutton.org/2.2/customize.html

**Comment by bernardnongpoh** [comment]
Thank you so much for your response
