### ISSUE TITLE
NOT A ISSUE 

### ISSUE THREAD

**Issue by iharshr** [toshke/big-blue-button-cloudformation-cfhl#19]
how do we go about installing custom version like 2.3.x something... 
can you plz guide me through it ...

ps: love ur project I'm using it for a year now no issues so far..... just want to use latest build of ubuntu 18 n bbb

**Comment by toshke** [comment]
hi @tetrex  haven't been really updating the project lately. By the looks of it Ubuntu 18.04 and bb.2.3 are the latest. I'd need to do some testing, but update process would look like following
- verify that install.sh script is still valid and works well on 18.04
- update the AMI base to 18.04 - see [here](https://github.com/toshke/big-blue-button-cloudformation-cfhl/blob/master/scripts/release_all.rb#L76) and [here](https://github.com/toshke/big-blue-button-cloudformation-cfhl/blob/master/scripts/release_all.rb#L56) 

P.S. Glad that people are consuming the solution, i.e  covid19  lockdown brainchild
